### ISSUE TITLE
[email protected] string in multiple titles

### ISSUE THREAD

**Issue by runecalico** [manami-project/modb-anime-planet#2]
Quite a few entries have [email protected] either as the name, or in part.

Replacing things like iDOLM@STER etc.

Perhaps it is a github security feature enabled in the repo that is automatically "protecting" email addresses?

Regardless, thought you should know :)

**Comment by manami-project** [comment]
Hi @runecalico,

thank you for reporting this issue. This is not a problem with any github settings. This occurs on anime-planet if a title contains an @ even if the string does not match any e-mail address format.

**Comment by runecalico** [comment]
Huh. That seems a bit silly on anime-planet's part. Well, thanks again for fixing it.
